baseURL = 'http://zanshin.net/'
languageCode = 'en-us'
title = 'Zanshin.net'

# RSS Limit, remove for unlimted
rssLimit = 20

# Pygments
PygmentsCodeFences = true
pygmentsUseClasses = false
PygmentsStyle = "native"

copyright = 'Copyright (c) 1996-{year}, Mark H. Nichols; all rights reserved'

[author]
  name = 'Mark H. Nichols'
  email = "mark@zanshin.net"

[permalinks]
  posts = '/:year/:month/:day/:title/'
  videos = '/:year/:month/:day/:title/'
  links = '/:year/:month/:day/:title/'

[params]
  owner = "Mark H. Nichols"
  description = "The personal site of Mark H. Nichols"

  Twitter = "zanshin"
  GitHub = "zanshin"
  Mastodon = "@zanshin"
  Email = "mark@zanshin.net"

  # RSS main sections
  mainSections = ["posts"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  # lineNoStart = 1
  # lineNos = true
  # lineNumbersInTable = true
  # tabWidth = 4
  # noClasses = false
  style = "native"

[menu]
  [[menu.main]]
  name = "About"
  url = "/about"
  weight = 1
  [[menu.main]]
  name = "Archive"
  url = "/posts/"
  weight = 2
  [[menu.main]]
  name = "Colophon"
  url = "/colophon"
  weight = 3
  [[menu.main]]
  name = "CIDR"
  url = "/cidr"
  weight = 4

  [[menu.alt]]
  name = "Music"
  url = "https://music.zanshin.net"
  weight = 1
  [[menu.alt]]
  name = "Books"
  url = "https://books.zanshin.net"
  weight = 2
  [[menu.alt]]
  name = "Geek"
  url = "https://geek.zanshin.net"
  weight = 3
  [[menu.alt]]
  name = "Password"
  url = "https://password.zanshin.net"
  weight = 4

  [[menu.other]]
  name = "Compositions"
  url = "https://compositions.sibyllekuder.com"
  weight = 1
  [[menu.other]]
  name = "Studio"
  url = "https://sibyllekuder.com"
  weight = 2

# Define media type
[mediaTypes]
  [mediaTypes."application/atom"]
    suffixes = ["xml"] # suffix key was deprecated

# Define output format
[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "atom"
  isPlainText = false

# Define additional outputs for home page (index)
[outputs]
  home = [ "HTML", "Atom" ]

